
test.js:
	python -m transcrypt -b -n test


feature.js:
	python -m transcrypt -p -b -n feature

feature_pipeline.js:
	python -m transcrypt -p -b -n feature_pipeline

train:
	python train.py

clean:
	rm -f test.js
	rm -f feature.js
	rm -f feature_pipeline.js
